"""Add missing Airflow secrets to .env with random values (never printed).

    python3 scripts/init_env.py
"""
import base64
import os
import secrets
from pathlib import Path

ENV = Path(__file__).resolve().parents[1] / ".env"

GENERATORS = {
    "AIRFLOW_DB_PASSWORD": lambda: secrets.token_urlsafe(24),
    "AIRFLOW_FERNET_KEY": lambda: base64.urlsafe_b64encode(os.urandom(32)).decode(),
    "AIRFLOW_SECRET_KEY": lambda: secrets.token_urlsafe(32),
    "AIRFLOW_ADMIN_PASSWORD": lambda: secrets.token_urlsafe(16),
}


def main():
    existing = ENV.read_text() if ENV.exists() else ""
    present = {line.split("=", 1)[0].strip() for line in existing.splitlines() if "=" in line}
    missing = [k for k in GENERATORS if k not in present]
    if missing:
        with ENV.open("a") as f:
            f.write("\n# Airflow (generated by scripts/init_env.py)\n")
            for key in missing:
                f.write(f"{key}={GENERATORS[key]()}\n")
        ENV.chmod(0o600)
    print(f"added: {', '.join(missing) or 'nothing'} (values written to {ENV.name} only)")


if __name__ == "__main__":
    main()
